# Generated by Django 3.0.6 on 2020-07-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
