# Generated by Django 3.0.6 on 2020-07-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200719_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='course',
        ),
    ]
