# Generated by Django 3.1.1 on 2021-04-11 23:17

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200815_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.log_directory_path),
        ),
    ]
